# Generated by Django 4.2.2 on 2023-06-08 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
