# Generated by Django 4.2.2 on 2023-06-08 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_order_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
