# Generated by Django 4.2.2 on 2023-06-09 06:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_order_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_thumbnail"
            ),
        ),
    ]
